"""
Corresponds to: error.hh

Exception hierarchy for the decompiler.
"""

from __future__ import annotations


class LowlevelError(Exception):
    """The lowest level error generated by the decompiler.

    This is the base error for all exceptions thrown by the decompiler.
    This underived form is thrown for very low-level errors that
    immediately abort decompilation (usually for just a single function).
    """

    def __init__(self, s: str = "") -> None:
        super().__init__(s)
        self.explain: str = s


class RecovError(LowlevelError):
    """A generic recoverable error.

    This error is the most basic form of recoverable error, meaning
    there is some problem that the user did not take into account.
    """
    pass


class ParseError(LowlevelError):
    """An error generated while parsing a command or language.

    This error is generated when parsing character data of some form,
    as in a user command from the console or when parsing C syntax.
    """
    pass


class DecoderError(LowlevelError):
    """An error while decoding a stream (marshal format)."""
    pass


class UnimplError(LowlevelError):
    """Exception for encountering unimplemented pcode.

    The particular instruction being decoded was valid, but the system
    doesn't know how to represent it in pcode.
    """

    def __init__(self, s: str = "", instruction_length: int = 0) -> None:
        super().__init__(s)
        self.instruction_length: int = instruction_length


class BadDataError(LowlevelError):
    """Exception for bad instruction data.

    The system cannot decode data for a particular instruction.
    """
    pass


class IfaceError(LowlevelError):
    """An error in the interface layer."""
    pass


class IfaceParseError(IfaceError):
    """Parsing error within the command interface."""
    pass


class IfaceExecutionError(IfaceError):
    """Execution error within the command interface."""
    pass
